services:
    Pazulx\JsonApiBundle\EventListener\ViewListener:
        arguments: ["@jms_serializer"]
        tags:
            - { name: kernel.event_listener, event: kernel.view }
    Pazulx\JsonApiBundle\EventListener\ApiExceptionListener:
        arguments: ["@jms_serializer"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    Pazulx\JsonApiBundle\EventListener\MethodNotAllowedExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    Pazulx\JsonApiBundle\EventListener\NotFoundExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    Pazulx\JsonApiBundle\EventListener\UnexpectedExceptionListener:
        arguments: ["@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -1 }
