imports:
    - { resource: event_listeners.yml }

services:
    rest_converter:
        class:        Pazulx\RESTBundle\Request\ParamConverter\RestRequestParamConverter
        arguments: ["@jms_serializer", "@validator"]
        tags:
            - { name: request.param_converter, priority: -2, converter: rest_converter }
