imports:
    - { resource: event_listeners.yml }

services:
    json_converter:
        class: '%param_converter_class%'
        arguments: ["@jms_serializer"]
        tags:
            - { name: request.param_converter, priority: -2, converter: json_converter }
